import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#a47cd0',
    alignItems: 'center',
  },
  backArrow: {
    transform: [{rotate: '90deg'}],
    alignSelf: 'flex-start',
    marginLeft: 10,
    marginTop: 5,
  },
  title: {
    fontWeight: 'bold',
    marginBottom: 5,
    color: '#fff',
    fontSize: 40,
  },
  subtitles: {
    color: '#fff',
    fontSize: 32,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  imageCard: {
    height: 220,
    width: 300,
    marginVertical: 25,
    resizeMode: 'contain',
  },
  titleColorSecond: {color: '#ffd600'},
  sectionCardContainer: {alignItems: 'center', marginHorizontal: 20},
  textsub: {color: '#fff', textAlign: 'center', fontSize: 17},
  benefitsContainer: {
    borderColor: '#ffd600',
    borderWidth: 1,
    width: 350,
    borderRadius: 20,
    backgroundColor: '#653f90',
    paddingHorizontal: 20,
    paddingVertical: 40,
  },
  backgroundText: {
    backgroundColor: '#8a5dbc',
    borderRadius: 8,
    width: 130,
    padding: 5,
  },

  membershipSaveText: {
    color: '#fff',
    fontSize: 12,
    textAlign: 'center',
  },
  textTitle: {color: '#fff', fontSize: 14, fontWeight: 'bold'},
  benefitsContain: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 8,
  },
  benefitsImages: {height: 15, width: 15, resizeMode: 'contain'},
  benefitsText: {color: '#fff', fontSize: 15, marginLeft: 10},
  boldText: {color: '#ffc201', fontWeight: 'bold'},
  smallText: {fontSize: 12},
  separator: {
    borderWidth: 0.5,
    borderColor: '#ffc200',
    marginVertical: 6,
  },
  membershipView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  textNormal: {fontWeight: 'normal'},
  textValue: {color: '#fff', fontWeight: 'bold', fontSize: 25},
  textCost: {color: '#fff', fontWeight: 'bold', fontSize: 15},
  buttonPrimary: {
    backgroundColor: '#ffc200',
    borderRadius: 12,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 10,
  },
  saveMargin: {marginVertical: 50},
  saveText: {color: '#fff', fontSize: 22, textAlign: 'center'},
  textConditions: {
    color: '#ffc200',
    fontSize: 10,
    textAlign: 'center',
    marginTop: 5,
  },
  input: {
    backgroundColor: '#bf93f1',
    color: '#fff',
    textAlign: 'center',
    fontSize: 18,
  },
  experiencesContain: {
    backgroundColor: '#653f90',
    flexDirection: 'row',
    borderRadius: 18,
    width: 350,
    minHeight: 170,
    marginVertical: 5,
    justifyContent: 'center',
    padding: 10,
  },
  experiencesImage: {
    resizeMode: 'contain',
    borderRadius: 10,
    width: 120,
    height: 140,
    margin: 5,
  },
  experiencesTitle: {
    color: '#fff',
    fontSize: 14,
    marginVertical: 5,
  },
  experiencesSubTitle: {color: '#fff', fontSize: 10},
  experienceTextAlign: {flexDirection: 'column', flex: 1},
  experienceContainer: {alignItems: 'center', marginBottom: 40},
  buttonText: {color: '#000', fontSize: 17, fontWeight: 'bold'},
});

export default styles;
